const modules = [
  {
    id: "prospects",
    name: "Prospects",
    subtitle: "Audit outreach",
    count: "30",
    title: "Find local businesses worth contacting today.",
    description:
      "Proofline can run your own growth routine: find local businesses with review gaps, generate a short audit, and suggest the next follow-up.",
    primary: "Generate audit batch",
    secondary: "Export outreach list",
    metrics: [
      ["Audits created", "30", "this week"],
      ["Opened reports", "9", "30%"],
      ["Replies", "3", "needs follow-up"],
      ["Best segment", "Cleaning", "highest signal"],
    ],
    rows: [
      {
        title: "Sparkle Home Cleaning - competitor review gap found",
        text: "Competitor added 18 recent reviews while Sparkle has 4 unanswered reviews and no fresh proof on the site.",
        tags: ["Cleaning", "High fit", "Audit ready"],
        tone: "good",
        action: "Open audit",
      },
      {
        title: "Northside Auto Detail - strong rating, weak response coverage",
        text: "Good candidate for reply setup and review request routine. Outreach email is ready.",
        tags: ["Auto", "Reply gap", "Email ready"],
        tone: "warn",
        action: "Send email",
      },
      {
        title: "Bright Dental - needs human check",
        text: "Healthcare category requires careful copy. Keep outreach focused on review replies and owner brief.",
        tags: ["Dental", "Sensitive", "Hold"],
        tone: "danger",
        action: "Review",
      },
    ],
    side: {
      title: "Founder GTM brief",
      items: [
        ["Today", "Send 20 audits to cleaning companies with unanswered reviews"],
        ["Best message", "Lead with competitor recent-review gap"],
        ["Avoid", "Long SaaS pitch or phone-first CTA"],
        ["CTA", "Let me set up the first review routine"],
      ],
    },
  },
  {
    id: "live",
    name: "Live Queue",
    subtitle: "API actions",
    count: "API",
    title: "Actions generated by the local automation engine.",
    description:
      "This module reads from the Proofline API. Approve and execute actions here to see status and audit trail change.",
    primary: "Refresh live queue",
    secondary: "Plan actions",
    metrics: [
      ["API state", "Loading", "waiting for local server"],
      ["Ready", "0", "actions"],
      ["Approval", "0", "need owner"],
      ["Executed", "0", "completed"],
    ],
    rows: [
      {
        title: "Start the local server to load live actions",
        text: "Run npm start, then refresh this module. Static fallback keeps the rest of the demo usable.",
        tags: ["API", "Waiting", "Demo"],
        tone: "warn",
        action: "Refresh",
      },
    ],
    side: {
      title: "What this proves",
      items: [
        ["API driven", "Actions are generated by rules and sample customer data"],
        ["Approval aware", "Sensitive actions cannot execute before approval"],
        ["Auditable", "Approvals and executions append log entries"],
      ],
    },
  },
  {
    id: "command",
    name: "Command Center",
    subtitle: "Owner queue",
    count: "18",
    title: "Every growth action, already prioritized.",
    description:
      "The AI operator turns reviews, replies, requests, referrals, repeats, sites, and compliance into one owner queue.",
    primary: "Approve safe actions",
    secondary: "Export owner brief",
    metrics: [
      ["Rating", "4.7", "+0.3 this quarter"],
      ["Open actions", "18", "5 need owner judgment"],
      ["Reviews this month", "42", "+31% vs baseline"],
      ["Pipeline influenced", "$8.4k", "referrals and repeats"],
    ],
    rows: [
      {
        title: "Recover Sarah M. before the issue becomes a public story",
        text: "Private reply mentions wait time, staff stress, and no manager check-in. Proofline drafted a call script, apology note, and recovery gift suggestion.",
        tags: ["Recovery", "Owner approval", "Evidence attached"],
        tone: "danger",
        action: "Open plan",
      },
      {
        title: "Send 14 review requests from completed jobs",
        text: "Eligible customers finished service, have consent, and have no open complaint. SMS and email copy are personalized by service type.",
        tags: ["Requests", "Ready", "Compliant"],
        tone: "good",
        action: "Send batch",
      },
      {
        title: "Publish John D.'s 5-star quote to homepage and Facebook",
        text: "Review mentions same-day service and careful cleanup. Proofline created a widget card and a short social post.",
        tags: ["Proof", "Social", "Website"],
        tone: "good",
        action: "Approve",
      },
      {
        title: "Fix weekend staffing message before Friday",
        text: "Wait-time complaints cluster on weekends after 5pm. Add arrival-window confirmation to the reminder sequence.",
        tags: ["Insight", "Operations", "Weekly brief"],
        tone: "warn",
        action: "Add to brief",
      },
    ],
    side: {
      title: "Autopilot summary",
      items: [
        ["Handled without owner", "27 requests sent, 9 follow-ups stopped, 3 replies drafted"],
        ["Needs judgment", "2 recovery calls, 1 privacy hold, 2 public reply approvals"],
        ["Next business move", "Promote same-day service proof on local landing page"],
      ],
    },
  },
  {
    id: "inbox",
    name: "Inbox",
    subtitle: "Reviews and replies",
    count: "24",
    title: "All reputation conversations in one customer timeline.",
    description:
      "Proofline brings Google reviews, private replies, review request responses, lead forms, and owner notes into one reputation inbox.",
    primary: "Review priority inbox",
    secondary: "Filter sources",
    metrics: [
      ["New signals", "24", "reviews, replies, forms"],
      ["Needs reply", "8", "public and private"],
      ["At-risk", "3", "owner attention"],
      ["Avg response", "38m", "this week"],
    ],
    rows: [
      {
        title: "Sarah M. replied by SMS after service",
        text: "Private feedback: wait time was too long, staff seemed overwhelmed. Linked to deep-cleaning job and recovery task.",
        tags: ["SMS reply", "At-risk", "Timeline"],
        tone: "danger",
        action: "Open timeline",
      },
      {
        title: "John D. left a 5-star Google review",
        text: "Mentions same-day service and careful cleanup. Reply draft and proof asset are ready.",
        tags: ["Google", "Promoter", "Proof"],
        tone: "good",
        action: "Open review",
      },
      {
        title: "Mike T. posted a 3-star Google review",
        text: "Booking instructions were confusing. Public reply draft and FAQ update are queued.",
        tags: ["Google", "Neutral", "Site fix"],
        tone: "warn",
        action: "Review draft",
      },
    ],
    cards: [
      {
        title: "Source filters",
        text: "Google, SMS, email replies, web forms, call notes, and imported customer feedback.",
        progress: 72,
      },
      {
        title: "Customer timeline",
        text: "Each signal connects to service history, message history, action queue, and audit log.",
        progress: 86,
      },
      {
        title: "Priority routing",
        text: "At-risk and high-value customers rise to the top before routine review replies.",
        progress: 79,
      },
    ],
    side: {
      title: "Timeline fields",
      items: [
        ["Customer", "Name, service, value, consent"],
        ["Signal", "Review, reply, form, note"],
        ["Action", "Reply, recover, ask, publish"],
        ["Evidence", "Original text and rule result"],
      ],
    },
  },
  {
    id: "requests",
    name: "Requests",
    subtitle: "SMS and email",
    count: "384",
    title: "Ask at the right moment, then stop when the customer responds.",
    description:
      "Proofline sends review requests from real business events, follows up politely, and protects opt-outs, replies, and open complaints.",
    primary: "Create request flow",
    secondary: "Import customers",
    metrics: [
      ["Sent this week", "384", "+18%"],
      ["Click rate", "34%", "+7 pts"],
      ["Public reviews started", "86", "+24"],
      ["Stopped safely", "23", "replies or opt-outs"],
    ],
    cards: [
      {
        title: "Completed job trigger",
        text: "Starts 90 minutes after service is marked complete. Uses service name, location, and technician tag.",
        progress: 92,
      },
      {
        title: "Follow-up rhythm",
        text: "Day 0 request, Day 3 reminder, Day 10 final thank-you. Stops on reply, review click, complaint, or opt-out.",
        progress: 78,
      },
      {
        title: "Manual VIP hold",
        text: "High-value customers can be held for owner personalization before any message is sent.",
        progress: 64,
      },
    ],
    rows: [
      {
        title: "Service completed: 14 customers eligible",
        text: "All customers have source, consent, and no unresolved issue. Copy variants are ready.",
        tags: ["Google", "SMS + email", "Batch"],
        tone: "good",
        action: "Preview",
      },
      {
        title: "Three customers replied instead of reviewing",
        text: "The sequence stopped automatically and created inbox tasks for the owner.",
        tags: ["Stopped", "Reply detected", "Safe"],
        tone: "warn",
        action: "Review",
      },
    ],
    flow: ["job.completed", "consent checked", "message sent", "follow-up", "review click", "report"],
  },
  {
    id: "recovery",
    name: "Recovery",
    subtitle: "Unhappy customers",
    count: "5",
    title: "Recover unhappy customers without crossing review policy lines.",
    description:
      "The recovery engine helps the owner respond well, fix root causes, and document the action. It does not hide, block, or discourage public reviews.",
    primary: "Open recovery board",
    secondary: "Export audit log",
    metrics: [
      ["Open recovery tasks", "5", "2 urgent"],
      ["Resolved this month", "18", "+7"],
      ["Avg response time", "38m", "-22m"],
      ["Root causes found", "4", "staffing, wait, billing, cleanup"],
    ],
    rows: [
      {
        title: "Sarah M. - wait time and overwhelmed front desk",
        text: "Suggested action: call within 2 hours, apologize clearly, offer service credit, and log staffing note for Friday.",
        tags: ["Urgent", "Call script ready", "Gift optional"],
        tone: "danger",
        action: "Open script",
      },
      {
        title: "Mike T. - parking confusion",
        text: "Suggested action: reply publicly with updated parking instructions and add FAQ block to microsite.",
        tags: ["Public reply", "Site update", "Low risk"],
        tone: "warn",
        action: "Approve",
      },
      {
        title: "Priya S. - issue resolved after owner follow-up",
        text: "Suggested action: send closure note, invite honest feedback, and add recovery win to weekly report.",
        tags: ["Resolved", "Closure", "Evidence"],
        tone: "good",
        action: "Close loop",
      },
    ],
    side: {
      title: "Recovery template",
      items: [
        ["Acknowledge", "Name the issue without arguing"],
        ["Own", "Explain the next concrete action"],
        ["Repair", "Offer fair resolution when appropriate"],
        ["Learn", "Tag the root cause for the weekly brief"],
      ],
    },
  },
  {
    id: "replies",
    name: "AI Replies",
    subtitle: "Review response",
    count: "11",
    title: "Reply in the brand voice, with evidence and approval controls.",
    description:
      "Proofline drafts public replies, private notes, escalation scripts, and staff recognition messages from the actual review text.",
    primary: "Approve reply drafts",
    secondary: "Edit brand voice",
    metrics: [
      ["Drafts ready", "11", "7 safe to approve"],
      ["Coverage", "72%", "+19 pts"],
      ["Sensitive holds", "3", "owner review required"],
      ["Brand voice score", "91%", "consistent"],
    ],
    rows: [
      {
        title: "5-star review: same-day service and cleanup",
        text: "Draft thanks the customer, repeats the service proof, and names the team value without sounding robotic.",
        tags: ["Safe draft", "Google", "Positive"],
        tone: "good",
        action: "Publish",
      },
      {
        title: "3-star review: booking instructions were confusing",
        text: "Draft acknowledges booking confusion and points to updated arrival instructions on the local page.",
        tags: ["Needs context", "Public", "Site link"],
        tone: "warn",
        action: "Edit",
      },
      {
        title: "2-star review: staff seemed overwhelmed",
        text: "Draft is held because it needs owner verification before public response.",
        tags: ["Hold", "Sensitive", "Owner"],
        tone: "danger",
        action: "Review",
      },
    ],
    preview: {
      label: "Draft reply",
      text:
        "Thank you for the honest feedback, Sarah. You should not have had to wait that long, and we are reviewing Friday staffing so this does not repeat. I would like to follow up directly and make this right.",
    },
  },
  {
    id: "proof",
    name: "Proof Library",
    subtitle: "Widgets and social",
    count: "31",
    title: "Turn good customer moments into proof assets everywhere.",
    description:
      "Public praise becomes widgets, microsite blocks, social posts, service page snippets, ad copy, and sales proof.",
    primary: "Approve proof assets",
    secondary: "Preview widget",
    metrics: [
      ["Approved assets", "31", "+6 this week"],
      ["Homepage widget CTR", "8.6%", "+1.4 pts"],
      ["Social posts queued", "5", "ready"],
      ["Service pages synced", "4", "live"],
    ],
    rows: [
      {
        title: "Homepage widget: same-day service",
        text: "John D.'s Google review is approved for homepage, local service page, and Facebook post.",
        tags: ["Widget", "Social", "Approved"],
        tone: "good",
        action: "Publish",
      },
      {
        title: "Recovered customer story",
        text: "Use as an internal owner brief item only. Customer name stays private unless approved.",
        tags: ["Privacy", "Recovery", "Internal"],
        tone: "warn",
        action: "Hold",
      },
      {
        title: "Staff recognition proof",
        text: "Three reviews mention careful cleanup. Proofline suggests a staff recognition post and hiring page quote.",
        tags: ["Staff", "Theme", "Growth"],
        tone: "good",
        action: "Create",
      },
    ],
    quotes: [
      ["Amazing same-day service and careful cleanup.", "John D."],
      ["They followed up quickly and made the issue right.", "Priya S."],
      ["The booking process was clear and easy.", "Alicia R."],
    ],
  },
  {
    id: "referrals",
    name: "Referrals",
    subtitle: "Happy customer loop",
    count: "9",
    title: "Ask happy customers to bring the next customer.",
    description:
      "The referral loop creates share links, tracks lead source, attributes booked revenue, and keeps reward rules separate from review incentives.",
    primary: "Launch referral loop",
    secondary: "Edit rewards",
    metrics: [
      ["Referral invites", "96", "+21"],
      ["Leads created", "17", "+5"],
      ["Booked jobs", "6", "$4.2k"],
      ["Reward cost", "$180", "tracked"],
    ],
    rows: [
      {
        title: "Promoters after 5-star public review",
        text: "Send referral ask 24 hours after thank-you reply. Include unique link and service-specific landing page.",
        tags: ["Active", "Google", "Trackable"],
        tone: "good",
        action: "Preview",
      },
      {
        title: "Recovered customer referral hold",
        text: "Proofline waits until the owner marks the recovery complete before suggesting any referral action.",
        tags: ["Hold", "Care first", "Safe"],
        tone: "warn",
        action: "Inspect",
      },
    ],
    flow: ["promoter detected", "reply sent", "referral ask", "lead form", "booked job", "reward tracked"],
  },
  {
    id: "repeats",
    name: "Repeats",
    subtitle: "Comeback timing",
    count: "22",
    title: "Bring customers back when the service cycle says they are ready.",
    description:
      "Repeat reminders use service type, last visit, seasonality, and customer response history to suggest the next booking moment.",
    primary: "Create repeat rule",
    secondary: "View calendar",
    metrics: [
      ["Repeat-ready customers", "22", "this week"],
      ["Reminder reply rate", "18%", "+4 pts"],
      ["Booked repeats", "8", "$3.1k"],
      ["Skipped contacts", "14", "cooldown protected"],
    ],
    cards: [
      {
        title: "Seasonal cleaning",
        text: "Suggest 90-day reminder for customers with deep-clean service and positive sentiment.",
        progress: 86,
      },
      {
        title: "Auto repair follow-up",
        text: "Suggest tire change reminder based on date, region, and last service category.",
        progress: 68,
      },
      {
        title: "Move-out cleaning cadence",
        text: "Use service-specific cadence, consent, and last-booked record before sending.",
        progress: 74,
      },
    ],
    rows: [
      {
        title: "18 customers due for seasonal cleaning reminder",
        text: "Proofline drafted one SMS and one email version with direct booking CTA.",
        tags: ["Repeat", "Ready", "Booking"],
        tone: "good",
        action: "Send",
      },
    ],
  },
  {
    id: "gifts",
    name: "Gifts",
    subtitle: "Loyalty and recovery",
    count: "4",
    title: "Use gifts as relationship care, not review payment.",
    description:
      "Proofline suggests thank-you and recovery gifts with compliance notes, cost tracking, and no condition tied to positive public reviews.",
    primary: "Configure gift rules",
    secondary: "View cost report",
    metrics: [
      ["Gift rules", "4", "active"],
      ["Sent this month", "12", "$312 cost"],
      ["Recovery gifts", "3", "owner approved"],
      ["Loyalty gifts", "9", "repeat customers"],
    ],
    rows: [
      {
        title: "Recovery credit for Sarah M.",
        text: "Suggested after verified poor experience. Message avoids asking for a positive review in exchange.",
        tags: ["Recovery", "Owner approval", "Policy-safe"],
        tone: "danger",
        action: "Approve",
      },
      {
        title: "Thank-you gift after third repeat booking",
        text: "Send a loyalty note and small gift card after repeat booking, not after a review rating.",
        tags: ["Loyalty", "Repeat", "Safe"],
        tone: "good",
        action: "Enable",
      },
    ],
    side: {
      title: "Gift rules",
      items: [
        ["Allowed", "Thank customers, recover real issues, reward loyalty"],
        ["Not allowed", "Pay for positive reviews or hide negative feedback"],
        ["Tracked", "Reason, amount, owner approval, message copy"],
      ],
    },
  },
  {
    id: "insights",
    name: "Insights",
    subtitle: "Owner intelligence",
    count: "7",
    title: "Explain what changed, why it matters, and what to do Monday.",
    description:
      "Insights combine reviews, private replies, campaigns, competitors, and local pages into a short owner-ready action brief.",
    primary: "Generate weekly brief",
    secondary: "Compare competitors",
    metrics: [
      ["Top issue share", "29%", "wait time"],
      ["Competitor gap", "24", "recent reviews"],
      ["Proof gap", "3 pages", "need reviews"],
      ["Action confidence", "87%", "evidence-backed"],
    ],
    cards: [
      {
        title: "Weekend wait time is the rating drag",
        text: "Mentions cluster Friday to Sunday after 5pm. Add arrival-window confirmation and staffing note.",
        progress: 88,
      },
      {
        title: "Competitors are winning on response speed",
        text: "Three local rivals gained review velocity with same-day response language.",
        progress: 74,
      },
      {
        title: "Your strongest proof is careful cleanup",
        text: "Use this phrase on homepage, cleaning service page, and first referral ask.",
        progress: 81,
      },
    ],
    chart: [38, 44, 51, 49, 63, 72, 81],
  },
  {
    id: "sites",
    name: "Microsites",
    subtitle: "Lead pages",
    count: "3",
    title: "Publish proof-rich pages that update from real reviews.",
    description:
      "Microsites combine ratings, approved quotes, FAQs, service proof, forms, click-to-call, campaign tracking, and local SEO copy.",
    primary: "Publish page update",
    secondary: "Preview microsite",
    metrics: [
      ["Live pages", "3", "synced"],
      ["Lead forms", "42", "+11"],
      ["Call clicks", "96", "+19%"],
      ["Proof blocks", "18", "approved"],
    ],
    rows: [
      {
        title: "Emergency cleaning page needs more recent proof",
        text: "Proofline selected two review snippets and one FAQ based on recent customer questions.",
        tags: ["SEO", "Lead page", "Draft"],
        tone: "warn",
        action: "Build",
      },
      {
        title: "Homepage proof band auto-updated",
        text: "New approved review added to widget and weekly report source list.",
        tags: ["Widget", "Live", "Synced"],
        tone: "good",
        action: "Preview",
      },
    ],
    site: true,
  },
  {
    id: "integrations",
    name: "Integrations",
    subtitle: "Event sources",
    count: "11",
    title: "Connect to business events first, then expand the app marketplace.",
    description:
      "The real value of 1000+ integrations is not the logo count. It is importing moments when the customer is ready for a request, recovery, repeat, referral, or proof asset.",
    primary: "Connect source",
    secondary: "View event log",
    metrics: [
      ["Connected", "5", "Google, CSV, Stripe, Zapier, HubSpot"],
      ["Events today", "148", "+36"],
      ["Mapped triggers", "12", "active"],
      ["Failed syncs", "0", "healthy"],
    ],
    integrations: [
      ["Google Business", "Reviews, profile, public reply workflow"],
      ["Stripe", "Paid invoice triggers and customer records"],
      ["Zapier / Make", "Bridge to 1000+ apps through events"],
      ["HubSpot", "Contacts, deals, lifecycle stage"],
      ["Jobber", "Field service job completed events"],
      ["Housecall Pro", "Home service appointments and jobs"],
      ["Square", "Payments and customer visit events"],
      ["QuickBooks", "Invoice paid and customer records"],
      ["Facebook", "Review monitoring and social publishing"],
      ["Yelp", "Monitoring and response workflow where allowed"],
      ["CallRail", "Call tracking, source, and lead attribution"],
    ],
    flow: ["app event", "normalize customer", "check consent", "choose loop", "send or queue", "measure result"],
  },
  {
    id: "compliance",
    name: "Compliance",
    subtitle: "Trust guardrails",
    count: "100%",
    title: "Make the risky parts visible, controlled, and auditable.",
    description:
      "Compliance is a product advantage. Owners see why a message was sent, paused, edited, or held before anything damages trust.",
    primary: "Export audit trail",
    secondary: "Review policies",
    metrics: [
      ["Review gating", "0", "not allowed"],
      ["Opt-outs protected", "100%", "required"],
      ["Messages logged", "1,284", "with source"],
      ["Sensitive holds", "7", "owner review"],
    ],
    rows: [
      {
        title: "No gating rule active",
        text: "Customers can always access public review links. Private recovery actions do not block honest feedback.",
        tags: ["Policy-safe", "Default", "Required"],
        tone: "good",
        action: "View",
      },
      {
        title: "Sensitive review held for owner approval",
        text: "Draft mentions refund and employee behavior, so Proofline requires a human check before publishing.",
        tags: ["Human review", "Sensitive", "Safe"],
        tone: "warn",
        action: "Review",
      },
      {
        title: "Gift rule includes compliance note",
        text: "Gift is tied to verified service recovery, not positive review outcome.",
        tags: ["Gift", "Audit", "Safe"],
        tone: "good",
        action: "Inspect",
      },
    ],
    side: {
      title: "Audit fields",
      items: [
        ["Who", "Customer, owner, staff, location"],
        ["What", "Trigger, message, channel, template"],
        ["Why", "Evidence, rule, AI reason, approval"],
        ["Outcome", "Reply, review, opt-out, referral, booking"],
      ],
    },
  },
];

const nav = document.querySelector("#moduleNav");
const moduleSelect = document.querySelector("#moduleSelect");
const panel = document.querySelector("#modulePanel");
const eyebrow = document.querySelector("#moduleEyebrow");
const title = document.querySelector("#moduleTitle");
const description = document.querySelector("#moduleDescription");
const primaryAction = document.querySelector("#primaryAction");
const secondaryAction = document.querySelector("#secondaryAction");
let suppressLiveHydrate = false;

function toneClass(tone) {
  if (tone === "good") return "is-good";
  if (tone === "warn") return "is-warn";
  if (tone === "danger") return "is-danger";
  return "";
}

function renderNav(activeId) {
  nav.innerHTML = modules
    .map(
      (module) => `
        <button class="module-button ${module.id === activeId ? "is-active" : ""}" type="button" data-module="${module.id}">
          <span>
            <b>${module.name}</b>
            <small>${module.subtitle}</small>
          </span>
          <em>${module.count}</em>
        </button>
      `,
    )
    .join("");

  if (moduleSelect) {
    moduleSelect.innerHTML = modules
      .map((module) => `<option value="${module.id}" ${module.id === activeId ? "selected" : ""}>${module.name}</option>`)
      .join("");
  }
}

function renderMetrics(metrics) {
  return `
    <div class="workspace-metrics">
      ${metrics
        .map(
          ([label, value, note]) => `
            <article>
              <span>${label}</span>
              <strong>${value}</strong>
              <small>${note}</small>
            </article>
          `,
        )
        .join("")}
    </div>
  `;
}

function renderRows(rows = []) {
  if (!rows.length) return "";
  return `
    <section class="workspace-card queue-card">
      <div class="card-heading">
        <div>
          <h2>Priority queue</h2>
          <p>Ordered by risk, timing, revenue impact, and confidence.</p>
        </div>
      </div>
      <div class="queue-list">
        ${rows
          .map(
            (row) => `
              <article class="queue-item ${toneClass(row.tone)} ${row.apiStatus ? `status-${row.apiStatus}` : ""}">
                <div>
                  <h3>${row.title}</h3>
                  <p>${row.text}</p>
                  <div class="tag-row">
                    ${row.tags.map((tag) => `<span>${tag}</span>`).join("")}
                  </div>
                </div>
                <button type="button" data-demo-action="${row.action}" data-action-id="${row.id || ""}" data-action-title="${row.title}">${row.action}</button>
              </article>
            `,
          )
          .join("")}
      </div>
    </section>
  `;
}

function renderCards(cards = []) {
  if (!cards.length) return "";
  return `
    <div class="mini-card-grid">
      ${cards
        .map(
          (card) => `
            <article class="workspace-card mini-card">
              <h3>${card.title}</h3>
              <p>${card.text}</p>
              <div class="progress" aria-label="${card.progress}% readiness">
                <span style="width:${card.progress}%"></span>
              </div>
            </article>
          `,
        )
        .join("")}
    </div>
  `;
}

function renderSide(side) {
  if (!side) return "";
  return `
    <aside class="workspace-card side-card">
      <h2>${side.title}</h2>
      <div class="side-list">
        ${side.items
          .map(
            ([label, value]) => `
              <div>
                <span>${label}</span>
                <p>${value}</p>
              </div>
            `,
          )
          .join("")}
      </div>
    </aside>
  `;
}

function renderFlow(flow = []) {
  if (!flow.length) return "";
  return `
    <section class="workspace-card flow-card">
      <div class="card-heading">
        <div>
          <h2>Automation path</h2>
          <p>The loop that runs after the trigger fires.</p>
        </div>
      </div>
      <div class="flow-row">
        ${flow.map((item, index) => `<span><b>${index + 1}</b>${item}</span>`).join("")}
      </div>
    </section>
  `;
}

function renderQuotes(quotes = []) {
  if (!quotes.length) return "";
  return `
    <section class="workspace-card quote-card">
      <div class="card-heading">
        <div>
          <h2>Approved proof</h2>
          <p>Ready for widgets, sites, reports, and social posts.</p>
        </div>
      </div>
      <div class="quote-grid">
        ${quotes
          .map(
            ([quote, source]) => `
              <article>
                <p>${quote}</p>
                <strong>${source}</strong>
              </article>
            `,
          )
          .join("")}
      </div>
    </section>
  `;
}

function renderPreview(preview) {
  if (!preview) return "";
  return `
    <section class="workspace-card reply-preview">
      <span>${preview.label}</span>
      <p>${preview.text}</p>
      <div class="reply-actions">
        <button type="button">Approve</button>
        <button type="button">Edit</button>
        <button type="button">Hold</button>
      </div>
    </section>
  `;
}

function renderChart(values = []) {
  if (!values.length) return "";
  const max = Math.max(...values);
  return `
    <section class="workspace-card chart-card">
      <div class="card-heading">
        <div>
          <h2>Signal trend</h2>
          <p>Combined review, reply, and action volume.</p>
        </div>
      </div>
      <div class="bar-chart">
        ${values
          .map((value) => `<span style="height:${Math.round((value / max) * 100)}%"><b>${value}</b></span>`)
          .join("")}
      </div>
    </section>
  `;
}

function renderSite() {
  return `
    <section class="workspace-card microsite-preview">
      <div>
        <span class="site-pill">4.8 average rating - 312 reviews</span>
        <h2>Trusted local cleaning, proven by recent customers.</h2>
        <p>Fresh proof blocks, FAQs, lead form, click-to-call, and source tracking update from approved Proofline assets.</p>
        <button type="button">Open public page</button>
      </div>
      <div class="site-review-stack">
        <p>Fast, careful, and easy to book again.</p>
        <p>The owner followed up and made it right.</p>
        <p>Same-day service saved our schedule.</p>
      </div>
    </section>
  `;
}

function renderIntegrations(items = []) {
  if (!items.length) return "";
  return `
    <section class="workspace-card integrations-card">
      <div class="card-heading">
        <div>
          <h2>Integration marketplace</h2>
          <p>Each app exists to feed useful customer events, not just decorate a logo wall.</p>
        </div>
      </div>
      <div class="integration-grid">
        ${items
          .map(
            ([name, value]) => `
              <article>
                <b>${name}</b>
                <span>${value}</span>
              </article>
            `,
          )
          .join("")}
      </div>
    </section>
  `;
}

function renderModule(module) {
  eyebrow.textContent = module.name;
  title.textContent = module.title;
  description.textContent = module.description;
  primaryAction.textContent = module.primary;
  secondaryAction.textContent = module.secondary;
  renderNav(module.id);

  const secondaryBlocks = [
    renderCards(module.cards),
    renderSide(module.side),
    renderFlow(module.flow),
    renderQuotes(module.quotes),
    renderPreview(module.preview),
    renderChart(module.chart),
    module.site ? renderSite() : "",
    renderIntegrations(module.integrations),
  ].join("");

  panel.innerHTML = `
    ${renderMetrics(module.metrics)}
    <div class="workspace-grid">
      ${renderRows(module.rows)}
      <div class="secondary-column">
        ${secondaryBlocks}
      </div>
    </div>
  `;

  if (module.id === "live" && !suppressLiveHydrate) {
    hydrateLiveQueue();
  }
}

nav.addEventListener("click", (event) => {
  const button = event.target.closest("[data-module]");
  if (!button) return;
  const nextModule = modules.find((module) => module.id === button.dataset.module);
  if (nextModule) renderModule(nextModule);
});

if (moduleSelect) {
  moduleSelect.addEventListener("change", () => {
    const nextModule = modules.find((module) => module.id === moduleSelect.value);
    if (nextModule) renderModule(nextModule);
  });
}

function showToast(message) {
  let toast = document.querySelector(".toast");
  if (!toast) {
    toast = document.createElement("div");
    toast.className = "toast";
    document.body.appendChild(toast);
  }

  toast.textContent = message;
  toast.classList.add("is-visible");
  window.setTimeout(() => toast.classList.remove("is-visible"), 2600);
}

function showActionDrawer({ title, action }) {
  let drawer = document.querySelector(".action-drawer");
  if (!drawer) {
    drawer = document.createElement("aside");
    drawer.className = "action-drawer";
    document.body.appendChild(drawer);
  }

  drawer.innerHTML = `
    <button class="drawer-close" type="button" aria-label="Close action drawer">Close</button>
    <p class="eyebrow">Action detail</p>
    <h2>${title}</h2>
    <p>This demo action now has a visible product response: owner approval, evidence trail, and audit state.</p>
    <div class="drawer-grid">
      <div><span>Status</span><b>Ready for owner</b></div>
      <div><span>Action</span><b>${action}</b></div>
      <div><span>Evidence</span><b>Review text, customer state, policy checks</b></div>
      <div><span>Audit</span><b>Decision recorded in demo log</b></div>
    </div>
    <div class="reply-actions">
      <button type="button" data-drawer-command="approve">Approve</button>
      <button type="button" data-drawer-command="execute">Execute</button>
      <button type="button" data-drawer-command="hold">Hold</button>
    </div>
  `;
  drawer.classList.add("is-open");
}

function renderActionEvidence(action) {
  const drawer = document.querySelector(".action-drawer");
  if (!drawer || !action) return;

  const latestAudit = action.audit || [];
  const payloadRows = Object.entries(action.payload || {})
    .filter(([, value]) => typeof value === "string" || typeof value === "number" || Array.isArray(value))
    .slice(0, 5)
    .map(([key, value]) => {
      const rendered = Array.isArray(value) ? value.join(", ") : String(value);
      return `<div><span>${key}</span><b>${rendered}</b></div>`;
    })
    .join("");

  drawer.innerHTML = `
    <button class="drawer-close" type="button" aria-label="Close action drawer">Close</button>
    <p class="eyebrow">Evidence-backed action</p>
    <h2>${action.title}</h2>
    <p>${action.payload?.reason || action.payload?.script || "Proofline generated this from customer evidence and policy rules."}</p>
    <div class="drawer-grid">
      <div><span>Status</span><b>${action.status.replaceAll("_", " ")}</b></div>
      <div><span>Type</span><b>${action.type.replaceAll("_", " ")}</b></div>
      <div><span>Approval</span><b>${action.approvalRequired ? "Required" : "Not required"}</b></div>
      <div><span>Priority</span><b>${action.priority}</b></div>
      ${payloadRows}
    </div>
    <div class="drawer-audit">
      <h3>Audit trail</h3>
      ${latestAudit
        .map(
          (item) => `
            <div>
              <b>${item.event}</b>
              <span>${new Date(item.at).toLocaleString()}</span>
              <p>${item.note}</p>
            </div>
          `,
        )
        .join("")}
    </div>
    <div class="reply-actions">
      <button type="button" data-drawer-command="approve">Approve</button>
      <button type="button" data-drawer-command="execute">Execute</button>
      <button type="button" data-drawer-command="hold">Hold</button>
    </div>
  `;
}

async function hydrateActionDrawer(actionId) {
  if (!actionId) return;
  try {
    const response = await fetch(`/api/actions/${actionId}`);
    if (!response.ok) return;
    const data = await response.json();
    renderActionEvidence(data.action);
  } catch {
    // Static fallback drawer is already visible.
  }
}

panel.addEventListener("click", (event) => {
  const button = event.target.closest("[data-demo-action]");
  if (!button) return;
  showActionDrawer({
    title: button.dataset.actionTitle,
    action: button.dataset.demoAction,
  });
  const drawer = document.querySelector(".action-drawer");
  if (drawer) {
    drawer.dataset.actionId = button.dataset.actionId || "";
  }
  hydrateActionDrawer(button.dataset.actionId);
  showToast(`${button.dataset.demoAction} opened with evidence and audit trail.`);
});

async function postJson(url) {
  const response = await fetch(url, {
    method: "POST",
    headers: { "content-type": "application/json" },
  });
  const data = await response.json();
  if (!response.ok) throw new Error(data.message || data.error || "Request failed.");
  return data;
}

function actionToRow(action) {
  const statusLabel = action.status.replaceAll("_", " ");
  return {
    id: action.id,
    title: action.title,
    text: action.payload?.reason || action.payload?.script || "Automation action generated from customer evidence and policy rules.",
    tags: [action.type.replaceAll("_", " "), statusLabel, action.approvalRequired ? "approval" : "ready"],
    tone: action.status === "executed" ? "good" : action.approvalRequired ? "danger" : "warn",
    action: action.status === "requires_approval" ? "Approve" : action.status === "approved" ? "Execute" : "Open",
    apiStatus: action.status,
  };
}

async function hydrateLiveQueue() {
  const liveModule = modules.find((module) => module.id === "live");
  if (!liveModule) return;

  try {
    const response = await fetch("/api/actions");
    if (!response.ok) throw new Error("API unavailable.");
    const data = await response.json();
    const actions = data.actions || [];
    const ready = actions.filter((action) => action.status === "ready").length;
    const approval = actions.filter((action) => action.status === "requires_approval").length;
    const executed = actions.filter((action) => action.status === "executed").length;

    liveModule.metrics = [
      ["API state", "Live", "local server connected"],
      ["Ready", String(ready), "actions"],
      ["Approval", String(approval), "need owner"],
      ["Executed", String(executed), "completed"],
    ];
    liveModule.rows = actions.map(actionToRow);
    liveModule.side = {
      title: "Latest audit trail",
      items: actions
        .slice(0, 4)
        .map((action) => [action.title, action.audit?.at(-1)?.event || "action.planned"]),
    };

    if (moduleSelect?.value === "live" || eyebrow.textContent === "Live Queue") {
      suppressLiveHydrate = true;
      renderModule(liveModule);
      suppressLiveHydrate = false;
    }
  } catch {
    showToast("Live API unavailable. Static demo still works.");
  }
}

document.addEventListener("click", async (event) => {
  const close = event.target.closest(".drawer-close");
  if (close) {
    close.closest(".action-drawer").classList.remove("is-open");
    return;
  }

  const command = event.target.closest("[data-drawer-command]");
  if (!command) return;
  const label = command.dataset.drawerCommand;
  const drawer = command.closest(".action-drawer");
  const actionId = drawer?.dataset.actionId;

  if (actionId && label === "approve") {
    try {
      await postJson(`/api/actions/${actionId}/approve`);
      showToast("Approved through the local API.");
      await hydrateLiveQueue();
      return;
    } catch (error) {
      showToast(error.message);
      return;
    }
  }

  if (actionId && label === "execute") {
    try {
      await postJson(`/api/actions/${actionId}/execute`);
      showToast("Executed through the local API.");
      await hydrateLiveQueue();
      return;
    } catch (error) {
      showToast(error.message);
      return;
    }
  }

  showToast(label === "approve" ? "Approved in demo mode." : label === "execute" ? "Executed in demo mode." : "Action held for later.");
});

primaryAction.addEventListener("click", async () => {
  if (eyebrow.textContent === "Live Queue") {
    await hydrateLiveQueue();
    showToast("Live queue refreshed.");
    return;
  }
  showToast(`${primaryAction.textContent} queued. Demo audit log updated.`);
});

secondaryAction.addEventListener("click", async () => {
  if (eyebrow.textContent === "Live Queue") {
    try {
      await postJson("/api/actions/plan");
      await hydrateLiveQueue();
      showToast("Actions replanned from sample data.");
      return;
    } catch (error) {
      showToast(error.message);
      return;
    }
  }
  showToast(`${secondaryAction.textContent} generated as a demo brief.`);
});

renderModule(modules[0]);
