const { customers, reviews, events } = require("./sample-data");
const {
  approvalRequired,
  canSendReviewRequest,
  canSuggestGift,
  isAtRisk,
  isPromoter,
} = require("./rules");

function findCustomerByName(name) {
  return customers.find((customer) => name && customer.name.toLowerCase() === name.toLowerCase());
}

function classifyReview(review) {
  const topics = [];
  const content = review.content.toLowerCase();

  if (/wait|late|arrival|overwhelmed/.test(content)) topics.push("Wait time");
  if (/booking|instruction|confusing|parking/.test(content)) topics.push("Instructions");
  if (/same-day|careful|cleanup|amazing/.test(content)) topics.push("Service proof");
  if (/followed up|made it right|resolved/.test(content)) topics.push("Recovery proof");

  return {
    sentiment: review.rating >= 5 ? "positive" : review.rating <= 3 ? "at_risk" : "neutral",
    risk: isAtRisk(review) ? "needs_attention" : "normal",
    topics,
    confidence: topics.length ? 0.84 : 0.62,
    evidence: [
      {
        sourceType: "review",
        sourceId: review.id,
        excerpt: review.content,
      },
    ],
  };
}

function createAction({ type, title, customer, review, priority, payload }) {
  const needsApproval = approvalRequired(type, review);

  return {
    id: `act-${type}-${review ? review.id : customer ? customer.id : "system"}`,
    type,
    title,
    customerId: customer ? customer.id : undefined,
    customerName: customer ? customer.name : review ? review.reviewerName : undefined,
    reviewId: review ? review.id : undefined,
    priority,
    status: needsApproval ? "requires_approval" : "ready",
    approvalRequired: needsApproval,
    evidenceIds: review ? [review.id] : [],
    payload,
    audit: [
      {
        at: new Date().toISOString(),
        event: "action.planned",
        note: "Generated by Proofline automation engine.",
      },
    ],
  };
}

function planActions() {
  const actions = [];

  for (const review of reviews) {
    const customer = findCustomerByName(review.reviewerName);
    const classification = classifyReview(review);

    if (classification.sentiment === "at_risk") {
      actions.push(
        createAction({
          type: "recovery_call",
          title: `Recover ${review.reviewerName}`,
          customer,
          review,
          priority: 96,
          payload: {
            reason: "At-risk feedback detected.",
            script: `Call ${review.reviewerName}. Acknowledge the issue, explain the fix, and log the root cause.`,
            classification,
          },
        }),
      );

      const giftDecision = canSuggestGift(review);
      if (giftDecision.allowed) {
        actions.push(
          createAction({
            type: "gift",
            title: `Review recovery gift for ${review.reviewerName}`,
            customer,
            review,
            priority: 72,
            payload: {
              reason: giftDecision.reason,
              giftType: "Service credit",
              maxValue: 25,
            },
          }),
        );
      }
    }

    if (isPromoter(review)) {
      actions.push(
        createAction({
          type: "publish_proof_asset",
          title: `Publish proof from ${review.reviewerName}`,
          customer,
          review,
          priority: 78,
          payload: {
            channels: ["Website widget", "Facebook draft", "Owner weekly brief"],
            quote: review.content,
            classification,
          },
        }),
      );

      actions.push(
        createAction({
          type: "send_referral_ask",
          title: `Queue referral ask for ${review.reviewerName}`,
          customer,
          review,
          priority: 64,
          payload: {
            timing: "24 hours after public thank-you reply",
            landingPage: "/r/brightclean",
          },
        }),
      );
    }
  }

  for (const customer of customers) {
    const requestDecision = canSendReviewRequest(customer);
    if (requestDecision.allowed) {
      actions.push(
        createAction({
          type: "send_review_request",
          title: `Send review request to ${customer.name}`,
          customer,
          priority: 70,
          payload: {
            reason: requestDecision.reason,
            channel: "SMS + email",
            template: `Hi ${customer.name}, thanks for choosing BrightClean. Would you mind sharing honest feedback about your recent ${customer.serviceType}?`,
          },
        }),
      );
    }

    if (!customer.openIssue && customer.lifetimeValue > 1500) {
      actions.push(
        createAction({
          type: "send_repeat_reminder",
          title: `Create repeat reminder for ${customer.name}`,
          customer,
          priority: 52,
          payload: {
            reason: "High-value repeat customer with service cadence due.",
            channel: "Email",
          },
        }),
      );
    }
  }

  return actions.sort((a, b) => b.priority - a.priority);
}

function createAuditForProspect({ businessName = "Local business", industry = "Cleaning", city = "Toronto" }) {
  return {
    id: `audit-${Date.now()}`,
    businessName,
    industry,
    city,
    score: 74,
    headline: `${businessName} has a reachable review-growth opportunity in ${city}.`,
    findings: [
      "Several recent reviews do not appear to have owner replies.",
      "Competitors are using fresh review language more clearly on service pages.",
      "A simple review request routine could increase recent review velocity within 30 days.",
    ],
    recommendedActions: [
      "Reply to the three most recent unanswered reviews.",
      "Send review requests to customers from the last 14 days.",
      "Publish two strong review quotes on the main service page.",
      "Track referral asks after 5-star reviews and resolved recovery moments.",
    ],
    outreachDraft: `Hi, I made a short review-growth audit for ${businessName}. I noticed a few easy wins around recent review replies, competitor review activity, and proof you could reuse on your site. If useful, I can help set up the first review routine this week.`,
  };
}

function executeAction(action) {
  if (!action) {
    return {
      ok: false,
      message: "Action not found.",
    };
  }

  if (action.approvalRequired && action.status !== "approved") {
    return {
      ok: false,
      message: "Action requires approval before execution.",
      action: {
        ...action,
        status: "requires_approval",
      },
    };
  }

  return {
    ok: true,
    message: "Demo action executed and audit log updated.",
    action: {
      ...action,
      status: "executed",
      audit: [
        ...action.audit,
        {
          at: new Date().toISOString(),
          event: "action.executed",
          note: "Executed in demo mode.",
        },
      ],
    },
  };
}

module.exports = {
  classifyReview,
  createAuditForProspect,
  executeAction,
  planActions,
  state: {
    customers,
    events,
    reviews,
  },
};
